name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Clone private dependency and build it
        run: |
          cd ..
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/samchamani/frontin.git frontin
          cd frontin
          npm install
          npm run build

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Hetzner
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SFTP_HOST }} >> ~/.ssh/known_hosts
          lftp -e "mirror -R --verbose --delete ./dist /public_html/simple-planner; bye" -u ${{ secrets.SFTP_USERNAME }}, sftp://${{ secrets.SFTP_HOST }}
